project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Lennart Oelschl&auml;ger"
  navbar:
    left:
      - icon: search
        text: "Research"
        href: research.qmd
      - icon: megaphone
        text: "Talks"
        href: talks.qmd
      - icon: sliders
        text: "Projects"
        href: projects.qmd
  search: false
  
format:
  html:
    theme: simplex
    link-external-icon: true
    link-external-filter: loelschlaeger.de|loelschlaeger.github.io|mailto
    
comments:
  utterances:
    repo: loelschlaeger/loelschlaeger.github.io
