project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  favicon: favicon-32x32.png
  search: false

lang: de

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    toc: false
    link-external-newwindow: true
