project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Lennart Oelschl&auml;ger"
  navbar:
    left:
      - icon: search
        text: "Research"
        href: research.qmd
      - icon: megaphone
        text: "Talks"
        href: talks.qmd
      - icon: sliders
        text: "Projects"
        href: projects.qmd
      - icon: pencil
        text: "Blog"
        href: https://loelschlaeger.de/blog
  search: false
  
format:
  html:
    theme: simplex
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/www\.loelschlaeger\.de\/custom
    
comments:
  utterances:
    repo: loelschlaeger/loelschlaeger.github.io
