project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - typewriter.js
    - profile-image.js
    - files/lennart_fliegen.jpeg
    - files/lennart_schach.jpeg

website:
  favicon: favicon-32x32.png
  search: false

lang: en

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    toc: false
    link-external-newwindow: true
    css: styles.css
    include-after-body: typewriter.html
