---
title: " "
pagetitle: "Lennart Oelschl&auml;ger"
output:
  html_document:
    toc: true
    toc_float: true
---

## Bayesian discrete choice modeling

## Initializing numerical optimization

## Financial hidden Markov models

Earning money with stock trading is utterly simple: one only needs to buy and sell stocks at the right moment. In general, stock traders seek to invest at the beginning of upward trends (commonly termed as bullish markets) and repel their stocks just in time before the prices fall again (bearish markets). 

Hidden Markov Models constitute a versatile class of statistical models for such time series data that is assumed to be dependent on latent states. In case of financial data, the latent states can be interpreted as different moods of the market. Even though these moods cannot be observed directly, price changes - which clearly depend on the current mood of the market - can be observed. Thereby, using an underlying Markov process, we can detect which mood is active at any point in time and how the different moods alternate. Depending on the current mood, a price change is generated by a different distribution. These distributions characterize the moods in terms of expected return and volatility.

In my [master thesis](files/master_thesis_oelschlaeger.pdf) in 2019 under the supervision of Roland Langrock, I applied the hierarchical extension of the hidden Markov model to German stock index data, aiming to improve the model's capability for distinguishing between short- and long-term trends and interpreting market dynamics at multiple time scales. Together with Timo Adam in 2020, [I published the work in the Journal of Statistical Modelling](https://doi.org/10.1177/1471082X211034048) and implemented the method in the [R Package fHMM](https://loelschlaeger.de/fHMM). Currently, together with Rouven Michels, we develop a package manual that we plan to publish in the Journal of Statistical Software.


