---
title: "My talks"
subtitle: "A list of my recent presentations at conferences and workshops."
comments: false
---

::: {.callout-note collapse="true" appearance="minimal"}
## Slides

- [Facilitating probit likelihood optimization](files/slides/statwo_12_09_2023.pdf), *Statistische Woche*, 12.09.2023

- [Initialization of numerical optimization in R](files/slides/yrw_07_09_2023.pdf), *12th Young Researcher Workshop at Bielefeld University*, 07.09.2023

- [Advances in the initialization of probit model estimation and the {ino} R package](files/slides/yrw_18_11_2022.pdf), *11th Young Researcher Workshop at Bielefeld University*, 18.11.2022

- [Modellierung ordinaler Pr&auml;ferenzen mit {RprobitB} am Beispiel des pairfam Panels](files/slides/aka_10_11_2022.pdf), *27. AKA-Workshop at Kloster Irsee*, 10.11.2022

- [Our contact points with big data in empirical methods](files/slides/doctoral_day_07_10_2022.pdf), *Doctoral Day at ZiF Bielefeld*, 07.10.2022 (with Carlina Feldmann and Jonas Bauer)

- [Bayes estimation of probit choice models with {RprobitB}](files/slides/yrw_11_03_2022/slides.html), *10th Young Researcher Workshop at Bielefeld University*, 10.03.2022

- [Klassifizierung von Pr&auml;ferenzen: Eine Anwendung mit dem R Paket RprobitB](files/slides/aka_18_11_2021.pdf), *26. AKA-Workshop at Kloster Irsee*, 18.11.2021

- [On the initialization of multinomial probit models](files/slides/yrw_16_07_2021.pdf), *9th Young Researcher Workshop at Bielefeld University*, 16.07.2021

- [Approximating mixing distributions in probit models via a Bayesian approach](files/slides/zest_24_11_2020.pdf), *Centre for Statistics at Bielefeld University*, 24.11.2020

- [Detecting bearish and bullish markets in financial time series using hierarchical hidden Markov models](files/slides/doctoral_day_02_10_2020.pdf), *Doctoral Day at Bielefeld University*, 02.10.2020
:::

::: {.callout-note collapse="true" appearance="minimal"}
## Posters

- [Bayesian probit models for preference classification](files/poster/IWSM2023-oelschlaeger-bauer-poster.pdf), *IWSM 2023*, 18.07.2023

- [Bayes estimation of latent class mixed multinomial probit models](files/poster/trb_28_01_2021.pdf), *Transportation Research Board Annual Meeting*, 28.01.2021
:::
