---
title: "My talks"
pagetitle: "Lennart Oelschl&auml;ger"
---

- [Our contact points with big data in empirical methods](files/slides/doctoral_day_07_10_2022.pdf), *Doctoral Day at ZiF Bielefeld*, 07.10.2022 (with Carlina Feldmann and Jonas Bauer)

- [Bayes estimation of probit choice models with {RprobitB}](files/slides/yrw_11_03_2022/slides.html), *10th Young Researcher Workshop at Bielefeld University*, 10.03.2022

- [Klassifizierung von Pr&auml;ferenzen: Eine Anwendung mit dem R Paket RprobitB](files/slides/aka_18_11_2021.pdf), *27. AKA-Workshop at Kloster Irsee*, 18.11.2021

- [On the initialization of multinomial probit models](files/slides/yrw_16_07_2021.pdf), *9th Young Researcher Workshop at Bielefeld University*, 16.07.2021

- [Bayes estimation of latent class mixed multinomial probit models](files/slides/trb_28_01_2021.pdf), *Poster Session at the 100th Transportation Research Board Annual Meeting*, 28.01.2021

- [Approximating mixing distributions in probit models via a Bayesian approach](files/slides/zest_24_11_2020.pdf), *Centre for Statistics at Bielefeld University*, 24.11.2020

- [Detecting bearish and bullish markets in financial time series using hierarchical hidden Markov models](files/slides/doctoral_day_02_10_2020.pdf), *Doctoral Day at Bielefeld University*, 02.10.2020

*Last update: `r Sys.Date()`*
