---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm, includeheadfoot

author: Lennart Oelschl&auml;ger
jobtitle: "Research Associate and PhD Student"
address: "Bielefeld University, Germany"
birthday: "16.11.1994"
motto: "Identify the essential. Eliminate the rest."
fontawesome: yes
email: oelschlaeger.lennart@gmail.com
github: loelschlaeger
twitter: l_oelschlaeger
phone: "+49 177 60 39 520"
web: loelschlaeger.de
updated: yes

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
lang: en-US
---

# Employment

Research Associate, *Bielefeld University* \hfill 2019 - current

# Education

Ph.D. Student in Econometrics, *Bielefeld University* \hfill 2019 - current

M.Sc. in Mathematical Economics, *Bielefeld University* \hfill 2017 - 2019

B.Sc. in Mathematics, *Bielefeld University* \hfill 2013 - 2017

# Publications

## Journal Articles

*Detecting bearish and bullish markets in financial time series using hierarchical hidden Markov models*, Oelschl&auml;ger and Adam (2021), Statistical Modelling

## Conference Papers

*Bayes Estimation of Latent Class Mixed Multinomial Probit Models*, Oelschl&auml;ger and Bauer (2021), TRB Annual Meeting

## Software

[fHMM](https://loelschlaeger.github.io/fHMM/): Fitting (hierarchical) hidden Markov models to financial data.

[RprobitB](https://loelschlaeger.github.io/RprobitB/): Bayesian estimation of (latent class mixed) multinomial probit models.

[ao](https://loelschlaeger.github.io/ao/): Alternating optimization of (high-dimensional) functions.

[vntrs](https://loelschlaeger.github.io/vntrs/): Variable neighborhood trust region search.

[ino](https://loelschlaeger.github.io/ino/): Initialization of numerical optimization.

# Talks

Klassifizierung von Pr&auml;ferenzen: Eine Anwendung mit dem R Paket RprobitB, *27. AKA-Workshop at Kloster Irsee*, 18.11.2021

On the initialization of multinomial probit models, *9th Young Researcher Workshop at Bielefeld University*, 16.07.2021

Approximating mixing distributions in probit models via a Bayesian approach, *Centre for Statistics at Bielefeld University*, 24.11.2020

Detecting bearish and bullish markets in financial time series using hierarchical hidden Markov models, *Doctoral Day at Bielefeld University*, 02.10.2020

# Teaching

Reading course for statistical science, *Bielefeld University* \hfill WT 21/22

Preparatory course for mathematics, *Bielefeld University* \hfill WT 21/22

Exercise course for mathematics, *Bielefeld University* \hfill WT 19/20, ST 20, WT 20/21, SS 21, WT 21/22

Tutorial for statistics, *Bielefeld University* \hfill WT 15/16, ST 16, WT 16/17, WT 18/19, ST 19

# Miscellanea

Aviation: I own a private pilot license. 

Chess: I play chess since I am 5 years old.

Tennis: Only outside and in good weather.

Languages: English, French, R, LaTeX, Markdown, C++, Matlab, Python, Java.

