on:
  push:
    paths:
      - 'cv/*'

jobs:
  render:
    name: Render CV
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install tinytex
        run: Rscript -e 'install.packages("tinytex"); tinytex::install_tinytex()'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render CV to cv folder
        run: Rscript -e 'rmarkdown::render("cv/oelschlaeger_cv.Rmd")'
      - name: Render CV to static folder
        run: Rscript -e 'rmarkdown::render("cv/oelschlaeger_cv.Rmd", output_dir = "files/")'
      - name: Commit results
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschläger"
          git add .
          git commit -m 'Update CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
